services:
  - type: web
    name: shrishtis-netflix-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: PUBLIC_API_URL
        value: https://shirishtisnetflix.onrender.com
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
